language: node_js
node_js: 
      - "stable"
before_install: cd apis/
install:
      - npm install
script:
      - npm test
cache:
  directories:
    - "node_modules"

after_success:
- npm run coverage
