language: node_js
node_js: 
      - "stable"
before_install: cd apis/
install:
      - npm install
script:
      - npm test
cache:
  directories:
    - "node_modules"

env: 
    - CODECLIMATE_REPO_TOKEN=dd8ff66cb3c35a9f1a51cf5131b20d2ed38ca05dbc4ca0b0604cc70468c4be65

after_success:
- npm run coverage
