language: node_js
node_js: 
      - "stable"
cache:
  directories:
    - "node_modules"

before_install: cd apis/
install:
      - npm install
services: 
      -postgresql
env: 
  global:
    - NODE_ENV=test
    - JWT_SECRET=themealappkey
    - CODECLIMATE_REPO_TOKEN=dd8ff66cb3c35a9f1a51cf5131b20d2ed38ca05dbc4ca0b0604cc70468c4be65
before_script:
      - psql -c 'create database mealApp;' -U postgres
      - psql -c 'CREATE USER root WITH PASSWORD password;' -U postgres
      - npm install -g sequelize-cli 
script:
      - npm run test

after_success:
- npm run coverage
